### ISSUE TITLE
Can't find your email address

### ISSUE THREAD

**Issue by george-adams1** [alexispomares/CV-chatbot#25]
Hey Alexis! Sorry to create an issue for this but I'm really interested in asking you a few questions and was unable to find your email address or another way to contact you. 

If you could provide one where I could contact you, I would really appreciate it!

George

**Comment by alexispomares** [comment]
Hey @george-adams1, sorry I'm just seeing this issue! I have my [LinkedIn profile](https://www.linkedin.com/in/alexispomares/) added to my GitHub account - feel free to reach out, if you're still interested in asking! :)
